---
- name: Install MetalLB
  hosts: k8s_control_plane
  become: true
  vars:
    kubeconfig: /home/{{ ansible_user }}/.kube/config
  tasks:

  - name: Install MetalLB
    command: >
      kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
    environment:
      KUBECONFIG: "{{ kubeconfig }}"

  - name: Wait for MetalLB pods to exist
    command: kubectl get pods -n metallb-system
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: metallb_pods
    retries: 20
    delay: 20
    until: "'controller' in metallb_pods.stdout"

  - name: Wait for MetalLB controller to stabilise
    shell: |
      kubectl get pods -n metallb-system --no-headers | grep controller | grep Running || true | wc -l
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: metallb_ready
    retries: 20
    delay: 20
    until: metallb_ready.stdout|int >= 1

  - name: Copy MetalLB config
    copy:
      src: "{{ playbook_dir }}/../files/k8s/metallb/metallb-config.yaml"
      dest: /tmp/metallb-config.yaml

  - name: Apply MetalLB config
    command: kubectl apply -f /tmp/metallb-config.yaml
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: metallb_config
    retries: 20
    delay: 20
    until: metallb_config.rc == 0

  - name: Convert ingress controller to LoadBalancer with static IP
    command: >
      kubectl patch svc ingress-nginx-controller
      -n ingress-nginx
      -p '{"spec":{"type":"LoadBalancer","loadBalancerIP":"192.168.1.70"}}'
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: ingress_patch
    retries: 20
    delay: 20
    until: ingress_patch.rc == 0