---
- name: Install MetalLB
  hosts: k8s_control_plane
  become: true

  tasks:

  - name: Install MetalLB
    command: >
      kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Wait for MetalLB controller to be ready
    command: >
      kubectl wait
      --namespace metallb-system
      --for=condition=Ready
      pod
      --selector=component=controller
      --timeout=300s
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Copy MetalLB config
    copy:
      src: "{{ playbook_dir }}/../files/k8s/metallb/metallb-config.yaml"
      dest: /tmp/metallb-config.yaml

  - name: Apply MetalLB config
    command: kubectl apply -f /tmp/metallb-config.yaml
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

  - name: Convert ingress controller to LoadBalancer with static IP
    command: >
      kubectl patch svc ingress-nginx-controller
      -n ingress-nginx
      -p '{"spec":{"type":"LoadBalancer","loadBalancerIP":"192.168.1.70"}}'
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf