apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  mariadb-root-password: "change-me-root"
  mariadb-database: "wordpress"
  mariadb-user: "wordpress"
  mariadb-password: "change-me-app"