apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: blog.lennardjohn.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
      - hostname: grafana.lennardjohn.org
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
      - service: http_status:404
